import { readFile, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { resolve } from 'node:path'

const root = resolve(import.meta.dir, '../..')
const languages = ['en', 'de', 'de-CH', 'es', 'es-419', 'fr', 'zh-Hans']
const catalogs: Record<string, Record<string, string>> = {}
for (const language of languages) catalogs[language] = JSON.parse(await readFile(resolve(root, 'localization', `${language}.json`), 'utf8'))
catalogs['de-AT'] = catalogs.de
catalogs['de-CH'] = { ...catalogs.de, ...catalogs['de-CH'] }
catalogs['es-419'] = { ...catalogs.es, ...catalogs['es-419'] }
const inventory: { usages: Record<string, { file: string; line: number }[]> } = JSON.parse(await readFile(resolve(root, 'localization/inventory.json'), 'utf8'))
const fingerprint = (text: string) => createHash('sha256').update(text).digest('hex')
const messages = Object.entries(catalogs.en).map(([id, source]) => ({ id, source, sourceHash: fingerprint(source),
  context: inventory.usages[id] ?? [], translations: Object.fromEntries(Object.entries(catalogs).filter(([locale]) => locale !== 'en').map(([locale, copy]) => [locale, {
    text: copy[id], translationHash: fingerprint(copy[id]), status: 'draft', reviewer: null,
  }])) }))
const packet = { policy: { weights: { meaning: 35, naturalness: 25, terminology: 15, tone: 15, readability: 10 },
  minimumWeightedScore: 4.5, minimumDimensionScore: 4, release: 'No unresolved critical or major defects; native review and rendered UI review required. AI checks do not confer approval.',
  protectedTerms: ['Mogging', 'mogging', 'looksmaxxing', 'Battle', 'Pro'],
  regionalScope: { de: ['Germany', 'Austria', 'Switzerland'], es: ['Spain', 'Latin America'], fr: ['All French-speaking countries'], 'zh-Hans': ['Simplified Chinese'] },
}, messages }
await writeFile(resolve(root, 'localization/review-packet.json'), JSON.stringify(packet, null, 2) + '\n')
const escape = (text: string) => text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')
const rows = messages.map(message => `<tr data-id="${escape(message.id)}"><td><code>${escape(message.id)}</code><small>${message.context.map(context => escape(`${context.file}:${context.line}`)).join('<br>') || 'Shared catalog; usage may be dynamic.'}</small></td><td>${escape(message.source)}</td>${Object.entries(message.translations).map(([locale, translation]) => `<td data-locale="${locale}">${escape(translation.text)}</td>`).join('')}</tr>`).join('\n')
await writeFile(resolve(root, 'localization/review.html'), `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Mogging — localization review</title><style>body{font:15px/1.6 system-ui;margin:32px;color:#18181b}header{max-width:850px}select,input{font:inherit;padding:10px;border:1px solid #ddd;border-radius:8px}table{border-collapse:collapse;width:100%;margin-top:24px}th,td{text-align:left;vertical-align:top;padding:16px;border-bottom:1px solid #ddd;min-width:240px}th{background:#f4f4f5}small{display:block;font-size:11px;color:#71717a;margin-top:8px}code{font-size:12px}[hidden]{display:none!important}.scroll{overflow:auto}</style><header><h1>Mogging localization review</h1><p>${messages.length} source messages. All translations are drafts awaiting native and in-product review. This packet covers shared homepage, demos, navigation, footer and selected welcome, personalization, settings and paywall copy; it does not represent a fully localized product.</p><p>Read each translation on its own for naturalness, then compare meaning, terminology and tone with English. German: Germany/Austria share wording; Switzerland has spelling overrides. Spanish: review Spain and Latin America separately. French: shared international wording, with regional validation still required.</p><label>Language <select id="language">${Object.keys(messages[0].translations).map(locale => `<option>${locale}</option>`).join('')}</select></label> <label>Filter <input id="filter" type="search" placeholder="Message ID or text"></label><p>Report corrections using the message ID. Scores: meaning 35%, naturalness 25%, terminology 15%, tone 15%, readability 10%. Target ≥4.5/5, each dimension ≥4; zero critical or major defects.</p></header><div class="scroll"><table><thead><tr><th>Message and context</th><th>English source</th>${Object.keys(messages[0].translations).map(locale => `<th data-locale="${locale}">${locale} · draft</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div><script>const language=document.getElementById('language'),filter=document.getElementById('filter');function update(){document.querySelectorAll('[data-locale]').forEach(cell=>cell.hidden=cell.dataset.locale!==language.value);document.querySelectorAll('tbody tr').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(filter.value.toLowerCase()))}language.onchange=update;filter.oninput=update;update()</script></html>`)
console.log(`Exported review packet for ${messages.length} messages; no approvals recorded.`)
const mobile: { candidates: { file: string; line: number; kind: string; text: string; context: string; sourceHash: string; triage: string }[] } = JSON.parse(await readFile(resolve(root, 'localization/mobile-inventory.json'), 'utf8'))
const mobileRows = mobile.candidates.map(candidate => `<tr data-triage="${candidate.triage}"><td><code>${escape(candidate.file)}:${candidate.line}</code><small>${escape(candidate.kind)} · ${candidate.triage}</small></td><td>${escape(candidate.text)}</td><td><code>${escape(candidate.context)}</code><small>Source hash: ${candidate.sourceHash}</small></td></tr>`).join('\n')
await writeFile(resolve(root, 'localization/mobile-review.html'), `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mogging mobile source reconciliation</title><style>body{font:15px/1.6 system-ui;margin:24px;color:#18181b}header{max-width:850px}input{font:inherit;padding:8px}table{border-collapse:collapse;width:100%}td,th{text-align:left;vertical-align:top;padding:12px;border-bottom:1px solid #ddd;min-width:200px}small{display:block;color:#71717a}code{font-size:12px;overflow-wrap:anywhere}.scroll{overflow:auto}[hidden]{display:none!important}</style><header><h1>Mogging mobile source reconciliation</h1><p>${mobile.candidates.length} review candidates. Includes code identifiers and false positives. This is a source inventory, not translated or approved copy, and not a coverage percentage.</p><p>Reconcile against mobile-scope.json. Assign semantic message IDs and screenshot context before translation. Native resources, generated reports, external providers and media need their own checks.</p><label>Filter by text or file <input id="filter" type="search"></label> <label><input id="includeCode" type="checkbox"> Include likely code values</label></header><div class="scroll"><table><thead><tr><th>Location</th><th>Candidate</th><th>Source context</th></tr></thead><tbody>${mobileRows}</tbody></table></div><script>const filter=document.getElementById('filter'),includeCode=document.getElementById('includeCode');function update(){const query=filter.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(row=>row.hidden=(!includeCode.checked&&row.dataset.triage==='likely-code-value')||!row.textContent.toLowerCase().includes(query))}filter.oninput=update;includeCode.onchange=update;update()</script></html>`)
