import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'

const root = resolve(import.meta.dir, '../..')
const source = resolve(root, 'localization')
const baseLanguages = ['en', 'de', 'es', 'fr', 'zh-Hans']
const catalogs: Record<string, Record<string, string>> = {}
for (const language of [...baseLanguages, 'de-CH', 'es-419']) {
  catalogs[language] = JSON.parse(await readFile(resolve(source, `${language}.json`), 'utf8'))
}
const english = catalogs.en
const tokens = (value: string) => [...value.matchAll(/{{\s*([^}]+)\s*}}/g)].map(match => match[1].trim()).sort().join('|')
for (const [language, catalog] of Object.entries(catalogs)) {
  if (baseLanguages.includes(language) && Object.keys(catalog).length !== Object.keys(english).length) throw new Error(`${language}: key count differs from English`)
  for (const [key, value] of Object.entries(catalog)) {
    if (!(key in english) || !value.trim()) throw new Error(`${language}: invalid key ${key}`)
    if (tokens(value) !== tokens(english[key])) throw new Error(`${language}: placeholders differ in ${key}`)
    for (const term of ['mogging', 'looksmaxxing', 'Stripe', 'iPhone', 'Pro', 'Battle']) {
      if ((key === 'landing.download' && term === 'iPhone') || (key === 'landing.webTitle' && term === 'Pro')) continue // Owner-approved marketing adaptations across locales.
      const pattern = new RegExp(`(?<![\\p{L}\\p{N}])${term}(?![\\p{L}\\p{N}])`, 'iu')
      if (pattern.test(english[key]) && !pattern.test(value)) throw new Error(`${language}: ${term} lost in ${key}`)
    }
    const numbers = (text: string) => [...text.matchAll(/\d+/g)].map(match => match[0]).join('|')
    if (numbers(value) !== numbers(english[key])) throw new Error(`${language}: numbers differ in ${key}`)
  }
}
catalogs['de-AT'] = catalogs.de
catalogs['de-CH'] = { ...catalogs.de, ...catalogs['de-CH'] }
catalogs['es-419'] = { ...catalogs.es, ...catalogs['es-419'] }
const generated = '// Generated by scripts/i18n/sync.ts. Edit localization/ instead.\n'
const files = {
  'catalogs.ts': `${generated}export const resources = ${JSON.stringify(Object.fromEntries(Object.entries(catalogs).map(([key, translation]) => [key, { translation }])), null, 2)} as const\n`,
  'locales.ts': generated + await readFile(resolve(source, 'locales.ts'), 'utf8'),
  'types.d.ts': generated + `import 'i18next'\nimport { resources } from './catalogs'\ndeclare module 'i18next' {\n  interface CustomTypeOptions {\n    defaultNS: 'translation'\n    keySeparator: false\n    strictKeyChecks: true\n    resources: { translation: Record<keyof typeof resources.en.translation, string> }\n  }\n}\n`,
}
for (const destination of [resolve(root, 'lib/i18n'), resolve(root, '../mogging-mobile/src/i18n')]) {
  await mkdir(destination, { recursive: true })
  for (const [name, contents] of Object.entries(files)) {
    const path = resolve(destination, name)
    if (process.argv.includes('--check')) {
      if (await readFile(path, 'utf8') !== contents) throw new Error(`Generated file is stale: ${path}`)
    } else await writeFile(path, contents)
  }
}
console.log(`Validated ${Object.keys(english).length} messages across ${Object.keys(catalogs).length} locales; generated catalogs ${process.argv.includes('--check') ? 'are current' : 'updated'}.`)
