// Generated by scripts/i18n/sync.ts. Edit localization/ instead.
import 'i18next'
import { resources } from './catalogs'
declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation'
    keySeparator: false
    strictKeyChecks: true
    resources: { translation: Record<keyof typeof resources.en.translation, string> }
  }
}
