import Link from 'next/link'
import { GuidePage } from '@/components/app/guide-page'

export default function FaceAnalysisGuide() {
  return (
    <GuidePage title="How Mogging face analysis works" description="Understand Mogging’s AI face reports, feature breakdowns, photo requirements, and scoring limitations before you upload a photo or compare results." path="/how-face-analysis-works">
      <p>Mogging generates an AI assessment from a face photo. The report organizes its output into feature categories and scores so you can inspect the details, rather than seeing only a single number. The mobile app also offers personalized routines and evaluation history.</p>
      <section>
        <h2>From photo to report</h2>
        <ol>
          <li><strong>Choose a clear photo.</strong> The face needs to be visible, with enough detail to assess its features. A heavily edited or obscured image is a poor starting point.</li>
          <li><strong>Generate an assessment.</strong> The analysis estimates visible traits from the image. It cannot directly measure your real-world anatomy or see what the photo does not show.</li>
          <li><strong>Read the breakdown.</strong> Review the feature descriptions and annotations alongside the score. If the description does not match the image, do not assume the model is right.</li>
          <li><strong>Compare consistent photos.</strong> Keep lighting, distance, pose, and expression similar when looking at changes over time.</li>
        </ol>
        <p>You can begin on the <Link href="/analysis">face analysis page</Link>. The <Link href="/">Mogging app</Link> brings reports, routines, and tracking together on mobile.</p>
      </section>
      <section>
        <h2>What the feature breakdown describes</h2>
        <p>Reports describe visible features such as the eyes, nose, mouth, jaw, and facial proportions. Broader categories include symmetry, angularity, skin appearance, and presentation. These are image-based estimates, not clinical examinations.</p>
        <p>The web report can show a PSL score on an eight-point scale and feature scores on a ten-point scale. Those scales serve different parts of the report and should not be treated as interchangeable. Neither is a population percentile or a medically validated measure of attractiveness.</p>
      </section>
      <section>
        <h2>Why the same face can receive different results</h2>
        <p>The input is a photograph, not the person themselves. Directional light creates shadows; a close camera changes how facial proportions appear; a tilted head changes visible alignment. Filters and image compression can also remove or alter detail. AI output itself can vary between assessments.</p>
        <p>A score changing between two photos does not establish a physical change. Before drawing a conclusion, compare the actual images and check whether the capture conditions changed.</p>
      </section>
      <section>
        <h2>A repeatable photo checklist</h2>
        <ul>
          <li>Use even lighting and avoid strong shadows across the face.</li>
          <li>Face the camera with a relaxed, consistent expression.</li>
          <li>Keep the camera at a similar height and distance each time.</li>
          <li>Use the original image without beauty filters or reshaping.</li>
          <li>Keep the face unobstructed and the image in focus.</li>
        </ul>
        <p>The useful comparison is between photos taken in comparable conditions. Chasing a higher number by changing camera angles makes progress harder to interpret.</p>
      </section>
      <section>
        <h2>What an AI face rating cannot tell you</h2>
        <p>A report cannot determine your worth, how everyone will perceive you, or whether you will have a particular social outcome. It cannot diagnose a skin condition, assess your health, or establish a need for a procedure. The app’s suggestions are not a substitute for individualized professional advice.</p>
        <p>Face analysis, <Link href="/battle">community votes</Link>, and <Link href="/what-is-mogging">mogging slang</Link> are three different things. A model score is generated by software; a vote reflects a visitor’s preference; slang expresses a social comparison. Combining them does not make any of them an objective measurement.</p>
      </section>
      <section>
        <h2>Your photos and shared reports</h2>
        <p>Read the <Link href="/privacy">privacy policy</Link> before uploading. Share links are intended to make a report accessible to people who receive the link; treat one as shareable information. Keeping a report out of search results does not make its URL private.</p>
        <p>For help with a photo, a report, or a deletion request, use <Link href="/support">Mogging support</Link>. This explanation describes the product, not independent validation of its accuracy.</p>
      </section>
    </GuidePage>
  )
}
