import { LegalPage, type LegalSection } from '@/components/app/legal-page'

const sections: LegalSection[] = [
  {
    id: 'overview',
    label: 'Overview',
    title: 'Privacy Overview',
    body: [
      'This Privacy Policy explains how Mogging collects, uses, stores, and shares information when you use the app, website, analysis tools, leaderboards, and related services.',
      'Because Mogging works with photos and appearance-analysis features, you should upload only content you have the right to use and only content you are comfortable submitting to the service.',
    ],
  },
  {
    id: 'information',
    label: 'Information We Collect',
    title: 'Information We Collect',
    body: [
      'We may collect information you provide directly, information generated by your use of the service, and technical information from your device or browser.',
      { items: ['Account details such as name, email, social links, profile attributes, and authentication identifiers.', 'Photos, analysis inputs, generated reports, rankings, votes, comparison results, and share links.', 'Payment status and checkout metadata from payment processors.', 'Device, log, IP, cookie, rate-limit, diagnostic, and security information.'] },
    ],
  },
  {
    id: 'use',
    label: 'How We Use Data',
    title: 'How We Use Information',
    body: [
      'We use information to operate Mogging, deliver analysis and ranking features, personalize app behavior, prevent abuse, improve reliability, process payments, and communicate with you.',
      'We may also use aggregated or de-identified information to understand feature performance and improve the product.',
    ],
  },
  {
    id: 'photos',
    label: 'Photos and Analysis',
    title: 'Photos, Analysis, and Visibility',
    body: [
      'Photos may be processed to create analysis reports, rankings, comparison pairs, profile images, and shareable previews depending on the feature you choose.',
      'Some controls may let you decide whether a photo participates in battle or leaderboard features. Public or shared pages can be viewed by anyone with access to the link.',
    ],
  },
  {
    id: 'sharing',
    label: 'Sharing',
    title: 'When Information Is Shared',
    body: [
      'We share information with service providers that help us run Mogging, including hosting, storage, database, authentication, analytics, security, and payment providers.',
      'We may disclose information if required by law, to protect rights and safety, to investigate abuse, or as part of a merger, acquisition, financing, or sale of assets.',
    ],
  },
  {
    id: 'retention',
    label: 'Retention',
    title: 'Retention and Deletion',
    body: [
      'We keep information for as long as needed to provide the service, comply with legal obligations, resolve disputes, enforce agreements, prevent abuse, and maintain backups.',
      'You can contact support@mogging.app to request access, correction, deletion, or help with account data. Some data may need to be retained where legally required or technically necessary.',
    ],
  },
  {
    id: 'security',
    label: 'Security',
    title: 'Security',
    body: [
      'We use reasonable administrative, technical, and organizational safeguards designed to protect information. No online service can guarantee absolute security.',
      'You should keep your account credentials private and notify us if you suspect unauthorized access.',
    ],
  },
  {
    id: 'contact',
    label: 'Contact',
    title: 'Contact Us',
    body: [
      'For privacy questions or data requests, email support@mogging.app with the subject Privacy Request and include the account email or relevant share link when available.',
    ],
  },
]

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Privacy"
      title="Privacy Policy"
      description="How Mogging handles account details, photos, analysis data, rankings, payments, device information, and support requests."
      updated="May 28, 2026"
      path="/privacy"
      sections={sections}
    />
  )
}
