import { LegalPage, type LegalSection } from '@/components/app/legal-page'

const sections: LegalSection[] = [
  {
    id: 'overview',
    label: 'Overview',
    title: 'Privacy Overview',
    body: [
      'This Privacy Policy explains how Mogging collects, uses, stores, and shares information when you use the app, website, analysis tools, leaderboards, and related services.',
      'Because Mogging works with face photos and appearance-analysis features, you should upload only content you have the right to use and only content you are comfortable submitting to the service.',
    ],
  },
  {
    id: 'information',
    label: 'Information We Collect',
    title: 'Information We Collect',
    body: [
      'We may collect information you provide directly, information generated by your use of the service, and technical information from your device or browser.',
      { items: ['Account details such as name, email, social links, profile attributes, and authentication identifiers.', 'Face photos you capture or select, local face landmark points generated from those photos, analysis inputs, generated reports, cosmetic scores, overlays, rankings, votes, comparison results, and share links.', 'Payment status and checkout metadata from payment processors.', 'Device, log, IP, cookie, rate-limit, diagnostic, and security information.'] },
    ],
  },
  {
    id: 'face-data',
    label: 'Face Data',
    title: 'Face Data We Collect and How We Collect It',
    body: [
      'Mogging does not collect Face ID data, TrueDepth sensor data, biometric faceprints, or persistent biometric templates. Mogging does collect face-related data when you choose to capture or upload a face image for a report.',
      { items: ['Face photos: the front-facing image you capture with the camera or select from your photo library.', 'Local landmark data: approximate points such as eyes, nose, mouth, jaw, face outline, and related geometry generated on device to align overlays and improve report consistency.', 'Report data: cosmetic analysis outputs such as PSL score, feature scores, visible skin-age cues, visible UV-context cues, report text, generated overlays, and share-card images.', 'Technical context: request IDs, account or anonymous session identifiers, timestamps, and basic device/network logs needed to process the request, prevent abuse, and troubleshoot errors.'] },
      'Face data is collected only after you take an action to upload, capture, analyze, save, or share a report. The app asks for camera, photo library, location, and third-party report-processing permission where those permissions are needed for the feature you choose.',
    ],
  },
  {
    id: 'use',
    label: 'How We Use Data',
    title: 'How We Use Information',
    body: [
      'We use information to operate Mogging, deliver analysis and ranking features, personalize app behavior, prevent abuse, improve reliability, process payments, and communicate with you.',
      'We may also use aggregated or de-identified information to understand feature performance and improve the product.',
    ],
  },
  {
    id: 'face-use',
    label: 'Face Data Use',
    title: 'How We Use Face Data',
    body: [
      'We use face photos and landmark data to prepare the image, confirm that a face is present, generate a cosmetic appearance report, place visual overlays, calculate report scores, save report history, create share-card images when you request sharing, and maintain abuse-prevention and support records.',
      'Mogging reports are cosmetic and entertainment-oriented appearance estimates. They are not medical, dermatology, health, employment, identity, or biometric identification advice, and they should not be used for high-stakes decisions.',
      'Some controls may let you decide whether a photo participates in battle, leaderboard, profile, or share-link features. Public or shared pages can be viewed by anyone with access to the link.',
    ],
  },
  {
    id: 'third-party-processing',
    label: 'Third-Party Processing',
    title: 'Third-Party Report Processing',
    body: [
      'When you consent to generate a face report, Mogging sends the selected face photo, any local face landmark points, the analysis prompt, and account or anonymous session identifiers to Mogging servers. Mogging then sends the face photo and prompt data to Moonshot/Kimi, our third-party analysis provider, which applies advanced learning and mathematical algorithms to generate the report response.',
      'We share this face data with Moonshot/Kimi only to provide the report feature you requested, improve request reliability, classify provider errors, and return the resulting cosmetic analysis to you. We do not ask the provider to identify you, verify your identity, infer sensitive traits, create a biometric template, or make medical diagnoses.',
      'Service providers that receive personal data from Mogging, including third-party analysis, hosting, storage, database, authentication, analytics, security, and payment providers, are required to protect the data they process for us with the same or equivalent privacy and security protections required by our agreements and applicable law.',
      'Moonshot/Kimi may process the submitted face photo and prompt data transiently to return the report output and may retain limited request logs as required by its service operations, security, abuse prevention, and legal obligations. Mogging does not authorize Moonshot/Kimi to use submitted face data to identify users or build biometric face profiles for Mogging.',
    ],
  },
  {
    id: 'sharing',
    label: 'Sharing',
    title: 'When Information Is Shared',
    body: [
      'We share information with service providers that help us run Mogging, including hosting, storage, database, authentication, analytics, security, and payment providers.',
      'We may disclose information if required by law, to protect rights and safety, to investigate abuse, or as part of a merger, acquisition, financing, or sale of assets.',
    ],
  },
  {
    id: 'retention',
    label: 'Retention',
    title: 'Face Data Retention and Deletion',
    body: [
      'Mogging does not retain Face ID data, TrueDepth data, biometric faceprints, or persistent biometric templates because the app does not collect those categories of face data.',
      'Mogging stores face photos, landmark points, report outputs, and share links so you can view prior reports, compare changes over time, generate share cards, receive support, and prevent abuse. This report-related face data is retained while your profile or report remains active, and in any event no longer than 12 months after your last account activity unless a longer period is required for security, legal compliance, dispute resolution, or fraud prevention.',
      'If you delete your profile in the app or request deletion at support@mogging.app, we delete or de-identify active account records, uploaded face photos, reports, landmarks, and share links tied to that profile. Active systems are targeted for deletion promptly after the request is processed, and backup copies are overwritten or removed on their normal cycle, generally within 90 days.',
      'Temporary processing files, local caches, and generated share images are kept only as long as needed to complete the request, improve performance, or support a current share action, and may be cleared automatically by the app, operating system, or server cache.',
    ],
  },
  {
    id: 'security',
    label: 'Security',
    title: 'Security',
    body: [
      'We use reasonable administrative, technical, and organizational safeguards designed to protect information. No online service can guarantee absolute security.',
      'You should keep your account credentials private and notify us if you suspect unauthorized access.',
    ],
  },
  {
    id: 'contact',
    label: 'Contact',
    title: 'Contact Us',
    body: [
      'For privacy questions or data requests, email support@mogging.app with the subject Privacy Request and include the account email or relevant share link when available.',
    ],
  },
]

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Privacy"
      title="Privacy Policy"
      description="How Mogging handles account details, photos, analysis data, rankings, payments, device information, and support requests."
      updated="June 14, 2026"
      path="/privacy"
      sections={sections}
    />
  )
}
