import { resolve } from 'node:path'

// The mobile catalog owns real protocol copy and scheduling. This checked-in
// snapshot lets CTA Studio use it without a runtime dependency on another repo.
const source = Bun.file(resolve(import.meta.dir, '../../mogging-mobile/src/lib/protocol-tasks.ts'))
const destination = resolve(import.meta.dir, '../lib/creator/protocol-tasks.ts')
const content = '// Generated by bun scripts/sync-protocol-tasks.ts. Edit mogging-mobile/src/lib/protocol-tasks.ts.\n' + await source.text()
if (process.argv.includes('--check')) {
  if (await Bun.file(destination).text() !== content) throw new Error('Protocol catalog is out of sync. Run bun scripts/sync-protocol-tasks.ts')
} else await Bun.write(destination, content)
