export type GuideExample = {
  id: string
  title: string
  hook: string
  explanation: string
  takeaway: string
  images: string[]
}

// Source order is retained so each example can be located in its reference document.
// Explanations and rewrite suggestions are Mogging editorial guidance, not source review notes.
export const positiveExamples: GuideExample[] = [
  { id: 'yes-1', title: 'Make potential the premise', hook: 'average “do I have potential” commenter', explanation: 'The Tom Welling edit explicitly frames the face as an example of potential. The pictured comments ask about potential and include viewers’ own faces.', takeaway: 'Build the hook around appearance. A Mogging version can invite viewers to explore their own feature breakdown. This source example is transcribed because its screenshot includes another app’s branding.', images: [] },
  { id: 'yes-2', title: 'Connect confidence to a looks transformation', hook: 'mfs after ascending and suddenly start approaching every girl with confidence', explanation: 'The premise names an ascent, and the source comments ask about ascending, potential, and facial traits. The intended subject is a change in appearance rather than generic confidence.', takeaway: 'Make the physical transformation explicit in the edit. Do not promise confidence or romantic success as a guaranteed result of Mogging. This source example is transcribed because its screenshot includes another app’s branding.', images: [] },
  { id: 'yes-3', title: 'Name the facial feature', hook: 'Upper Eyelid Exposure', explanation: 'The image labels a specific feature. Viewers discuss how much of that feature they have and ask appearance-related questions.', takeaway: 'A clear feature label gives the viewer a reason to think about their own face. Demonstrate the relevant Mogging analysis without inventing treatment claims.', images: ['yes-3'] },
  { id: 'yes-4', title: 'Make attractiveness the comparison', hook: 'POV: you’re prime megan fox for girls', explanation: 'The comparison is explicitly about attractiveness. The pictured comments include personal potential questions.', takeaway: 'Keep the comparison about appearance rather than fame, a character, or a scene. Add a readable Mogging product moment and CTA.', images: ['yes-4'] },
  { id: 'yes-5', title: 'Show an appearance comparison', hook: 'The Morph:', explanation: 'The reference presents an altered appearance and discussion of looks. Its inclusion illustrates a looks-related premise, not proof that the pictured change is real.', takeaway: 'Clearly identify a morph or illustrative edit. Never present a manipulated face as an actual Mogging result or a guaranteed transformation.', images: ['yes-5'] },
  { id: 'yes-6', title: 'Compare appearance over time', hook: 'POV: you both aged like wine but this was you in your primes', explanation: 'The text directs attention to changing attractiveness over time. The comments discuss looks, “prime,” and ascending.', takeaway: 'Keep the before-and-after comparison central and truthful. Avoid turning it into a general celebrity nostalgia montage.', images: ['yes-6'] },
  { id: 'yes-7', title: 'Put the glow-up ahead of the backstory', hook: 'when instead of depression after a breakup you chose a crazy glow up', explanation: 'A breakup provides context, but the named subject is a glow-up. Viewers respond with their own before pictures and potential questions.', takeaway: 'Show the appearance change clearly. A breakup caption alone would not qualify, and Mogging must not be presented as a treatment for depression.', images: ['yes-7'] },
  { id: 'yes-8', title: 'Explicitly frame attractiveness', hook: 'when you’re so attractive girls don’t even try anymore', explanation: 'The source labels attractiveness directly, and the pictured audience asks about their own potential.', takeaway: 'The relevant lesson is the explicit looks premise. Prefer a specific feature or appearance explanation over unsupported claims about other people’s behavior.', images: ['yes-8'] },
  { id: 'yes-9', title: 'Make improvement visible', hook: 'when you glowed up so hard that girls start pulling up to you naturally', explanation: 'The text centers a glow-up and attracts potential-related comments.', takeaway: 'Show what changed in appearance. Keep any Mogging claims accurate; do not guarantee attention, dates, or social outcomes.', images: ['yes-9'] },
  { id: 'yes-10', title: 'Shift the subject to your own appearance', hook: 'POV: life when you stopped chasing fine shyt and became fine shyt', explanation: 'The source frames becoming attractive as the subject, and comments include personal appearance questions and photos.', takeaway: 'For a clearer Mogging adaptation: “When you start understanding your own features.” Pair it with an actual product demonstration instead of relying on a social scene alone.', images: ['yes-10'] },
  { id: 'yes-11', title: 'Start a specific feature discussion', hook: '“Big nose doesn’t matter”', explanation: 'The text names a facial feature. The comments discuss viewers’ noses rather than the song or celebrity alone.', takeaway: 'Use the feature as an educational starting point. Avoid claiming that one trait determines someone’s worth or that the app guarantees a physical change.', images: ['yes-11'] },
  { id: 'yes-12', title: 'Focus the camera prompt on appearance', hook: 'DON’T MOVE YOUR CAMERA LET’S SEE WHAT YOU LOOK LIKE RIGHT NOW', explanation: 'The prompt is about how the viewer looks, and the example shows potential questions in the comments.', takeaway: 'The appearance connection must remain clear. Do not turn the prompt into “interact to improve your looks” or manufacture photo replies.', images: ['yes-12'] },
  { id: 'yes-13', title: 'A clear before-and-after sequence', hook: '“Same guy btw”', explanation: 'The final two source images form a transformation example. Their juxtaposition makes appearance change the subject even with a short hook.', takeaway: 'Use a genuine, accurately described comparison. Do not misrepresent two different people, a morph, lighting changes, or a fictional result as a real transformation caused by Mogging.', images: ['yes-13', 'yes-14'] },
]

export const negativeExamples: GuideExample[] = [
  { id: 'no-1', title: 'A glow-up promised for engagement', hook: 'your glow up when you return to school after summer depends on how you treat this video', explanation: 'The comments are dominated by “claim” responses. The premise trades a promised glow-up for interaction instead of attracting genuine interest in appearance.', takeaway: 'Remove the engagement bargain. Show a real appearance change or feature breakdown, then invite viewers to try Mogging. The source hook is transcribed because the screenshot includes another app’s branding.', images: [] },
  { id: 'no-2', title: 'Romantic success in exchange for actions', hook: 'your crush wants you just as much as you want them … they will finally ask you out by the end of summer if you do all', explanation: 'The post promises a romantic outcome for engagement. The comments say “claim” rather than discussing looks.', takeaway: 'Neither an attractive celebrity nor a dating premise makes this looks content. Remove the promise and build an explicit appearance-focused concept.', images: ['no-2'] },
  { id: 'no-3', title: 'Three notifications and sound use', hook: 'POV: your life this summer with fine shyt because you gave me 3 notifications and used sound (can be private)', explanation: 'The desired action is engagement, and the comments repeat claims. The footage does not turn that bargain into a looks-focused video.', takeaway: 'Do not reward likes, comments, or sound use with promised confidence, attractiveness, or romantic outcomes.', images: ['no-3'] },
  { id: 'no-4', title: 'A dating joke over a TV scene', hook: 'how I start moving when bro introduces me to his 10/10 sister (I’m plotting on her)', explanation: 'The joke is about a situation. The pictured comments react to the song and show, not personal appearance or improvement.', takeaway: 'Using “10/10” somewhere in the caption is not enough. The subject of the edit must actually be looks.', images: ['no-4'] },
  { id: 'no-5', title: 'A character or actor debate', hook: 'Henry Cavill thinks he is the last son of Krypton:', explanation: 'The central premise is Superman casting and fandom. Even incidental appearance comparisons in the comments do not change that premise.', takeaway: 'Make the actor’s features or attractiveness the explicit subject. A few looks-related comments cannot rescue an unrelated fan edit.', images: ['no-5'] },
  { id: 'no-6', title: 'A social-media dating situation', hook: 'When she gives you her insta but doesn’t accept your request', explanation: 'Viewers discuss follow requests and the song. The attractive person is background to a dating meme.', takeaway: 'A Mogging CTA appended to this would not be enough. Rewrite the premise around a specific feature, potential, or genuine transformation.', images: ['no-6'] },
  { id: 'no-7', title: '“Ascend” used as engagement bait', hook: 'POV: DO ALL for you to ascend like this during summer', explanation: 'The word “ascend” sounds relevant, but the offer still conditions improvement on interaction. The comments are claims.', takeaway: 'Looks vocabulary does not override the ban on engagement farms. Sports-focused edits are also currently excluded.', images: ['no-7'] },
  { id: 'no-8', title: 'Summer anticipation', hook: 'How life feels now because tomorrow is finally summer', explanation: 'The audience discusses summer and school. The caption has no appearance-focused idea.', takeaway: '“My appearance progress this summer” could be a new looks concept only if the footage actually demonstrates it.', images: ['no-8'] },
  { id: 'no-9', title: 'Song nostalgia', hook: 'how life felt when this song was hits', explanation: 'Viewers react to and ask about the song. The person shown does not make the topic looks-related.', takeaway: 'Music can support a looks edit, but the song cannot be the entire premise.', images: ['no-9'] },
  { id: 'no-10', title: 'A music reaction', hook: 'how it feels lister to spanish song', explanation: 'The caption and responses center the song and the joke, not appearance.', takeaway: 'Replace the unrelated hook with a truthful feature or transformation premise and make the footage support it.', images: ['no-10'] },
  { id: 'no-11', title: 'A texting joke', hook: 'your text was so good she’s been reading it for 2 days', explanation: 'The joke is about an unanswered message. Viewers respond to the situation rather than their looks.', takeaway: 'Do not rely on the attractiveness of the person shown. The actual content needs an explicit looks focus.', images: ['no-11'] },
  { id: 'no-12', title: 'An exam meme', hook: 'How I feel walking into the french exam knowing this is the only thing I know', explanation: 'The audience reacts to school, the sound, and sports references. There is no appearance premise.', takeaway: 'School and sports memes are not a substitute for a looks-focused concept.', images: ['no-12'] },
  { id: 'no-13', title: 'School-year relief', hook: 'how it feels finishing this school year without studying', explanation: 'Comments discuss studying and exams. Tom Welling’s appearance is incidental to the school joke.', takeaway: 'The same celebrity can appear in qualifying and non-qualifying edits. The framing is what changes the audience.', images: ['no-13'] },
  { id: 'no-14', title: 'Losing feelings', hook: 'How I feel because I lost feelings for her', explanation: 'The text and comments concern relationships. No feature, attractiveness, improvement, or potential is the subject.', takeaway: 'A relationship story can be context for a genuine glow-up, but it cannot replace the looks-focused substance.', images: ['no-14'] },
  { id: 'no-15', title: 'Summer with a friend', hook: 'How life’s gonna feel this summer with that one bro', explanation: 'Viewers tag friends and discuss summer. This is friendship content even though the same footage could be used in a different kind of edit.', takeaway: 'Compare this with the camera/appearance example: what the text asks viewers to think about changes the audience.', images: ['no-15'] },
]
