// Generated by bun scripts/sync-protocol-tasks.ts. Edit mogging-mobile/src/lib/protocol-tasks.ts.
/** Evidence notes: docs/protocol-task-research.md. Keep copy and scheduling here;
 * CTA Studio receives this module through its sync script. */
export const protocolProductOptions = [
  { id: 'cleanser', label: 'Gentle cleanser' },
  { id: 'moisturizer', label: 'Fragrance-free moisturizer' },
  { id: 'uv-protection', label: 'Broad-spectrum SPF 30+' },
  { id: 'vitamin-c', label: 'Vitamin C serum' },
  { id: 'retinol', label: 'Retinol / prescribed retinoid' },
  { id: 'salicylic-acid', label: 'Salicylic acid' },
  { id: 'azelaic-acid', label: 'Azelaic acid' },
  { id: 'exfoliant', label: 'Gentle exfoliant' },
] as const
export type ProtocolProductId = (typeof protocolProductOptions)[number]['id']
export const protocolDefaultProducts: readonly ProtocolProductId[] = ['cleanser', 'moisturizer', 'uv-protection']
export const protocolActiveProducts: readonly ProtocolProductId[] = ['vitamin-c', 'retinol', 'salicylic-acid', 'azelaic-acid', 'exfoliant']

export type ProtocolTask = {
  key: string
  title: string
  detail: string
  tips: string[]
  time: 'Morning' | 'Midday' | 'Evening' | 'Anytime'
  hour: number
  icon: { ios: string; android: string }
  color: string
  focusIds: string[]
  priority: number
  weekdays?: number[]
  product?: ProtocolProductId
  family?: string
}

const icons = {
  posture: { ios: 'figure.stand', android: 'accessibility_new' },
  strength: { ios: 'figure.strengthtraining.traditional', android: 'fitness_center' },
  skin: { ios: 'drop.fill', android: 'water_drop' },
  sun: { ios: 'sun.max.fill', android: 'wb_sunny' },
  eyes: { ios: 'eye.fill', android: 'visibility' },
  mouth: { ios: 'mouth.fill', android: 'mood' },
  nose: { ios: 'nose.fill', android: 'air' },
  grooming: { ios: 'scissors', android: 'content_cut' },
  recovery: { ios: 'sparkles', android: 'auto_awesome' },
}
function task(key: string, title: string, detail: string, tips: string[], focusIds: string[], kind: keyof typeof icons, time: ProtocolTask['time'], extra: Partial<ProtocolTask> = {}): ProtocolTask {
  const colors = { posture: '#32c48d', strength: '#26b86b', skin: '#48c7ff', sun: '#f5b73f', eyes: '#8c7cff', mouth: '#ff6f9f', nose: '#00a8ef', grooming: '#111113', recovery: '#ef5da8' }
  return { key, title, detail, tips, focusIds, time, hour: time === 'Morning' ? 8 : time === 'Evening' ? 16 : 12, icon: icons[kind], color: colors[kind], priority: 60, ...extra }
}
const skinFocus = ['skin-age', 'skin-quality', 'sun-damage', 'overall']
const definitionFocus = ['jaw', 'facial-fat', 'cheekbones', 'face-shape', 'overall']

export const protocolTasks: ProtocolTask[] = [
  task('neck-posture', '10 gentle chin tucks', 'Sit upright. Slide your chin straight back, hold 3 seconds, then release. Repeat 10 times with your teeth apart.', ['Keep the movement small; do not tip the chin down.', 'Stop for pain, dizziness, tingling, or numbness.', 'This trains neck posture; it does not reshape jawbones.'], ['jaw', 'face-shape', 'symmetry'], 'posture', 'Morning'),
  task('shoulder-blade', '10 shoulder-blade squeezes', 'Gently draw both shoulder blades back and down. Hold 5 seconds, relax, and repeat 10 times.', ['Keep your ribs relaxed rather than arching your back.', 'Use both sides equally and stay within a comfortable range.', 'Builds postural control around the neck and shoulders.'], ['jaw', 'symmetry', 'dimorphism', 'face-shape'], 'posture', 'Midday'),
  task('wall-slides', '8 controlled wall slides', 'Stand with your back near a wall. Slide both arms upward through a comfortable range for 8 slow repetitions.', ['Do not force your wrists or shoulders against the wall.', 'Stop if the shoulder pinches; a physiotherapist can adapt the movement.', 'Improves shoulder mobility, not facial bone symmetry.'], ['symmetry', 'dimorphism', 'face-shape'], 'posture', 'Midday'),
  task('jaw-release', '2-minute jaw relaxation', 'Set a 2-minute timer. Keep your teeth apart and release jaw tension while breathing comfortably.', ['Do not press your tongue hard against the palate.', 'Avoid jaw trainers, prolonged gum chewing, and clenching.', 'Persistent jaw pain, locking, or bite changes need a dental assessment.'], ['jaw', 'mouth', 'symmetry'], 'mouth', 'Evening'),
  task('jaw-habit', 'Replace one clenching trigger', 'During desk work, set three reminders to release clenched teeth and drop tense shoulders. Replace nail biting or prolonged gum chewing with a short break.', ['Use relaxed teeth-apart rest rather than forceful jaw exercise.', 'Do not change a prescribed splint without your dentist.', 'Reduces avoidable strain; it does not enlarge or straighten the jaw.'], ['jaw', 'symmetry'], 'posture', 'Midday'),
  task('targeted-shoulders', '2 sets of lateral raises', 'Using light dumbbells or a resistance band, do 2 sets of 8–12 controlled lateral raises. Rest about a minute between sets.', ['Lift only to a comfortable height without shrugging.', 'Leave a couple of repetitions in reserve and stop for pain.', 'Builds shoulder musculature over time; it does not masculinize facial bones.'], ['dimorphism', 'face-shape', 'overall'], 'strength', 'Evening', { weekdays: [2, 5], family: 'strength' }),
  task('band-rows', '2 sets of resistance-band rows', 'Secure a band using its manufacturer-approved anchor. Perform 2 sets of 8–12 rows with elbows close to your sides.', ['Check the band and anchor before starting.', 'Pull smoothly without jerking or arching your lower back.', 'Supports upper-back strength and an upright neck/shoulder frame.'], ['dimorphism', 'face-shape', 'overall'], 'strength', 'Evening', { weekdays: [2, 5], family: 'strength' }),
  task('brisk-walk', '20-minute brisk walk', 'Walk for 20 minutes at a pace where you can talk but not comfortably sing. Begin with a shorter duration if you are new to exercise.', ['Build regular activity gradually; protect exposed skin outdoors.', 'Do not use sweat, dehydration, or crash dieting to chase facial definition.', 'Supports overall fitness; fat cannot be selectively removed from the face.'], definitionFocus, 'strength', 'Midday'),
  task('balanced-meal', 'Build one balanced meal', 'Add a protein food, vegetables or fruit, and a whole-grain or other fiber-rich carbohydrate to one meal today.', ['Examples: beans and vegetables with rice, or yogurt with oats and fruit.', 'Maintain enough food for your needs; do not skip meals to sharpen your face.', 'Supports sustainable nutrition rather than targeting cheek or jaw fat.'], ['facial-fat', 'cheekbones', 'overall'], 'recovery', 'Midday'),
  task('sodium-swap', 'Swap one salty packaged food', 'Compare two similar food labels and choose the lower-sodium option for one snack or meal.', ['Keep eating normally; do not eliminate sodium or restrict water.', 'Follow any clinician-prescribed fluid or salt guidance.', 'May help fluid-related puffiness; it does not change facial fat or bone.'], ['facial-fat', 'eyes', 'cheekbones', 'overall'], 'recovery', 'Midday'),
  task('sleep-window', 'Protect your sleep window', 'Set a consistent bedtime and a 30-minute wind-down alarm. Allow 7–9 hours for adults, or 8–10 hours for teens.', ['Keep the wake-up time consistent and put your phone away during wind-down.', 'Persistent snoring, breathing pauses, or daytime sleepiness deserve medical review.', 'Supports recovery; it will not remove inherited under-eye hollows.'], ['eyes', 'facial-fat', 'skin-age', 'overall'], 'recovery', 'Evening'),
  task('eye-depuff', '5-minute cool eye compress', 'Rest a clean cloth cooled with water over closed eyes for 5 minutes when they are puffy. Use light contact without pressure.', ['Use cool, not frozen, material; never put ice directly on the eyelids.', 'Stop if uncomfortable. Pain, marked redness, or vision changes need prompt care.', 'This can temporarily ease puffiness; it does not change eye shape.'], ['eyes'], 'eyes', 'Morning'),
  task('eye-break', '20-20-20 screen breaks', 'Set a reminder during screen work: every 20 minutes, look at something about 20 feet away for 20 seconds and blink normally.', ['Avoid rubbing your eyes or forcing a wide-eyed expression.', 'Persistent dryness or irritation needs an eye-care assessment.', 'Helps eye comfort and dryness rather than changing canthal tilt.'], ['eyes'], 'eyes', 'Midday'),
  task('eyelid-clean', 'Remove eye makeup gently', 'If you wear eye makeup, remove it before bed with a product labeled for the eye area and a clean pad. Keep pressure light.', ['Skip this task if you do not wear eye makeup.', 'Do not use retinol, exfoliating acids, or fragranced facial products on the eyelids.', 'Reduces leftover residue that can irritate the eye area.'], ['eyes'], 'eyes', 'Evening'),
  task('brow-groom', 'Comb and tidy brow hairs', 'Use a clean spoolie to comb your brows. Trim only obvious long stray hairs with small grooming scissors if you are comfortable doing so.', ['Work slowly away from the eye; skip trimming if unsure.', 'Preserve the natural brow outline and avoid over-plucking.', 'Balances brow grooming without promising to correct facial asymmetry.'], ['eyes', 'symmetry', 'dimorphism'], 'grooming', 'Morning', { weekdays: [2, 6] }),
  task('lip-mouth', 'Seal dry lips with petrolatum', 'Apply a thin layer of plain, fragrance-free petrolatum to dry lips after washing and before bed.', ['Stop licking, biting, and peeling loose lip skin.', 'Avoid tingling or fragranced balms if your lips are irritated.', 'Helps chapping and surface dryness; it does not enlarge lips.'], ['mouth'], 'mouth', 'Evening'),
  task('lip-spf', 'SPF 30+ lip balm', 'Before outdoor time, apply a lip balm with broad-spectrum SPF 30 or higher. Reapply every 2 hours outdoors.', ['Cover the full exposed lip surface and reapply after eating or drinking.', 'Choose a non-irritating formula; stop if it burns.', 'Protects lip skin from UV exposure.'], ['mouth', 'sun-damage'], 'sun', 'Morning'),
  task('dental-brush', 'Brush for 2 minutes', 'Use a soft-bristled manual or electric toothbrush and fluoride toothpaste. Brush gently for 2 minutes; repeat morning and before bed.', ['Clean every surface and the gumline without scrubbing hard.', 'Spit out toothpaste; avoid immediately rinsing it away.', 'Supports clean teeth and gum health, not changes to lip or jaw anatomy.'], ['mouth', 'jaw', 'overall'], 'mouth', 'Evening'),
  task('interdental', 'Clean between teeth', 'Once today, gently clean between teeth using floss or correctly sized interdental brushes.', ['Slide floss in a C-shape along each tooth instead of snapping it into the gums.', 'Ask a dentist about persistent bleeding or discomfort.', 'Removes plaque where a toothbrush cannot reach.'], ['mouth', 'overall'], 'mouth', 'Evening'),
  task('nose-saline', 'Saline spray for congestion', 'If your nose is blocked or dry, use a pharmacy-prepared saline nasal spray according to its label. Otherwise skip this task.', ['Do not share the nozzle or force breathing through a blocked nose.', 'For a rinse device, use distilled, sterile, or previously boiled and cooled water.', 'Relieves nasal symptoms; it will not narrow the nose or straighten its bridge.'], ['nose'], 'nose', 'Morning'),
  task('nose-groom', 'Tidy visible nostril hairs', 'If needed, use a guarded nose trimmer to trim only hairs protruding beyond the nostril opening.', ['Do not pluck hairs or insert the tool deeply.', 'Clean the tool according to its instructions and stop for irritation.', 'A grooming step rather than a change to nose structure.'], ['nose', 'dimorphism'], 'grooming', 'Morning', { weekdays: [3] }),
  task('gentle-cleanser', 'Gentle evening cleanse', 'Massage a gentle cleanser over damp facial skin with your fingertips, rinse with lukewarm water, and pat dry.', ['Remove sunscreen and makeup without brushes or gritty scrubs.', 'Use a fragrance-free option if easily irritated; do not scrub oily nose pores.', 'Removes residue while limiting unnecessary irritation.'], [...skinFocus, 'nose'], 'skin', 'Evening', { product: 'cleanser', family: 'skin-basic' }),
  task('skin-barrier', 'Moisturize face and neck', 'Apply a fragrance-free moisturizer with ingredients such as glycerin or ceramides to slightly damp facial skin and neck.', ['Use a richer cream for dryness or a lighter non-comedogenic formula if acne-prone.', 'If skin stings or peels, pause irritating actives and use gentle care.', 'Supports the skin barrier and reduces dry, rough surface texture.'], skinFocus, 'skin', 'Evening', { product: 'moisturizer', family: 'skin-basic' }),
  task('uv-spf', 'Broad-spectrum SPF 30+', 'Apply broad-spectrum, water-resistant SPF 30 or higher to exposed face, ears, and neck before outdoor time.', ['Follow the label and cover all exposed skin, including the nose.', 'Reapply every 2 hours outdoors and after swimming or sweating.', 'Helps prevent further UV damage; improvements take consistent use.'], [...skinFocus, 'nose'], 'sun', 'Morning', { product: 'uv-protection', priority: 80 }),
  task('uv-shade', 'Pack UV protection', 'Put a wide-brimmed hat and UV-protective sunglasses by the door, and plan shaded routes for outdoor time.', ['Sunscreen works alongside shade and clothing.', 'Protect skin on cloudy days too; avoid tanning beds.', 'Reduces UV exposure around the eyes, nose, and face.'], ['sun-damage', 'skin-age', 'eyes', 'nose'], 'sun', 'Morning'),
  task('vitamin-c', 'Vitamin C serum morning', 'If this is your chosen, tolerated active, apply a vitamin C serum as directed, then moisturizer and daytime SPF.', ['Introduce one active at a time and test a small area before regular use.', 'Skip irritated skin and keep the serum away from eyelids and lip edges.', 'May improve uneven pigmentation over time; it does not replace sunscreen.'], skinFocus, 'skin', 'Morning', { product: 'vitamin-c', weekdays: [1, 4], family: 'skin-active' }),
  task('retinol', 'Retinol night', 'If appropriate for you, use your chosen retinol as labeled on dry facial skin, then moisturizer. This starter plan includes two separated nights weekly.', ['Avoid during pregnancy or while trying to conceive; ask your clinician about breastfeeding.', 'Use daytime SPF. Avoid eyelids and lip/nose creases; skip irritated skin, acids, and other retinoids that night.', 'If under 18 or treating acne, ask a clinician which treatment fits. Follow prescribed dosing instead of this starter schedule.'], skinFocus, 'skin', 'Evening', { product: 'retinol', weekdays: [1, 4], family: 'skin-active' }),
  task('salicylic-acid', 'Salicylic acid for clogged pores', 'If you have blackheads or clogged pores and already tolerate this chosen product, use salicylic acid on the affected areas according to its label.', ['Do not use on eyelids, broken skin, or sunburn; skip if it irritates.', 'Do not combine with another exfoliant or retinoid in this starter routine.', 'Targets clogged pores, including on the nose; it does not shrink nose cartilage.'], ['nose', 'skin-age', 'skin-quality', 'overall'], 'skin', 'Evening', { product: 'salicylic-acid', weekdays: [2, 5], family: 'skin-active' }),
  task('azelaic-acid', 'Azelaic acid for acne marks', 'If acne or post-acne marks are your concern and this is your chosen, tolerated product, apply azelaic acid as its label or clinician directs.', ['Test tolerance first and avoid eyelids, lips, and broken skin.', 'If it burns or causes persistent irritation, pause and seek advice.', 'Can help acne and its dark marks; facial scores cannot diagnose these conditions.'], skinFocus, 'skin', 'Evening', { product: 'azelaic-acid', weekdays: [2, 5], family: 'skin-active' }),
  task('exfoliant', 'Gentle exfoliant night', 'Only if your chosen exfoliant suits your skin, use it as labeled tonight, then moisturizer. The starter plan uses one night weekly.', ['Do not exfoliate irritated, sunburned, or broken skin.', 'Skip scrubs, retinoids, and other acids in the same routine.', 'Optional surface care; more frequent use is not automatically better.'], skinFocus, 'skin', 'Evening', { product: 'exfoliant', weekdays: [3], family: 'skin-active' }),
  task('grooming-edges', 'Maintain facial-hair edges', 'If you have facial hair, use a guarded trimmer to tidy the neckline and cheek edges while keeping a shape you like.', ['Skip if you do not have facial hair; avoid plucking ingrown hairs.', 'Keep tools clean and avoid repeated close passes on irritated skin.', 'Improves grooming around the lower face without changing underlying bones.'], ['jaw', 'dimorphism', 'face-shape', 'overall'], 'grooming', 'Morning', { weekdays: [0, 4] }),
  task('bite-assessment', 'Plan a bite assessment', 'If your bite feels uneven, your jaw locks, or one side has persistent pain, arrange an assessment with a dentist instead of trying one-sided chewing exercises.', ['Skip this task if you have no symptoms or concerns.', 'Do not use DIY bite devices or try to move teeth yourself.', 'Structural asymmetry needs an individual assessment, not a generic exercise promise.'], ['jaw', 'symmetry'], 'mouth', 'Midday', { weekdays: [3], priority: 45 }),
]

export function normalizeProtocolProducts(products: readonly ProtocolProductId[]): ProtocolProductId[] {
  const known = new Set<ProtocolProductId>(protocolProductOptions.map(option => option.id))
  const unique = [...new Set(products)].filter(product => known.has(product))
  const active = unique.find(product => protocolActiveProducts.includes(product))
  return unique.filter(product => !protocolActiveProducts.includes(product) || product === active)
}

export function selectProtocolTasks({ focusIds, date, count = 3, skinProducts = [], uvIndex = 0 }: {
  focusIds: readonly string[]; date: string; count?: number; skinProducts?: readonly ProtocolProductId[]; uvIndex?: number
}): ProtocolTask[] {
  const calendarDate = new Date(`${date}T12:00:00`)
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(calendarDate.getTime()) || formatProtocolDate(calendarDate) !== date) throw new Error('Choose a valid protocol date')
  const weekday = calendarDate.getDay()
  const ordinal = Math.floor(Date.UTC(calendarDate.getFullYear(), calendarDate.getMonth(), calendarDate.getDate()) / 86_400_000)
  const products = new Set(normalizeProtocolProducts(skinProducts))
  const focus = new Set(focusIds.length ? focusIds : ['overall'])
  const candidates = protocolTasks.filter(task => (!task.weekdays || task.weekdays.includes(weekday)) && (!task.product || products.has(task.product)))
  const focused = candidates.filter(task => task.focusIds.some(id => focus.has(id)))
  const selected: ProtocolTask[] = []
  const add = (task: ProtocolTask | undefined) => {
    if (!task || selected.length >= count || selected.some(item => item.key === task.key || (task.family && item.family === task.family))) return
    selected.push(task)
  }
  // A selected active stays on its planned days, and UV protection has priority.
  add(focused.find(task => task.family === 'skin-active'))
  if ([...focus].some(id => skinFocus.includes(id)) || uvIndex >= 3) add(candidates.find(task => task.key === 'uv-spf') ?? candidates.find(task => task.key === 'uv-shade'))
  const offset = ((ordinal % Math.max(1, focused.length)) + focused.length) % Math.max(1, focused.length)
  for (let i = 0; i < focused.length && selected.length < Math.min(count, 2); i++) add(focused[(offset + i) % focused.length])
  const support = candidates.filter(task => ['skin-barrier', 'gentle-cleanser', 'sleep-window', 'brisk-walk', 'balanced-meal', 'uv-spf'].includes(task.key))
  const pools = [support, focused]
  for (const pool of pools) for (let i = 0; i < pool.length && selected.length < count; i++) add(pool[(ordinal + i) % pool.length])
  return selected
}

export function formatProtocolDate(date: Date) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
}

/** Preserve the mobile calendar's evenly spaced, nonoverlapping task cards. */
export function scheduleProtocolTasks<T extends ProtocolTask>(items: T[], startHour: number) {
  const preferredHour = (item: T) => Math.max(7, Math.min(16, Math.round(item.hour)))
  const sorted = [...items].sort((a, b) => preferredHour(a) - preferredHour(b) || b.priority - a.priority)
  const slots = sorted.length <= 1 ? [10] : sorted.length === 2 ? [7, 16] : sorted.length === 3 ? [7, 12, 16] : [7, 10, 13, 16]
  return sorted.map((item, index) => {
    const hour = Math.max(startHour, slots[index] ?? 16)
    const nextHour = slots[index + 1] ?? 19
    return { item, hour, durationHours: Math.min(1.35, Math.max(0.78, nextHour - hour - 0.18)) }
  })
}
